name: Action Schedule

on:
  schedule:
      - cron: '0 * * * *'
  #push:
  #  branches:
  #    - master
  workflow_dispatch:
    inputs:
      cashhack:
        description: 'API key for my Hatena Blog'
        required: true

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
        env:
          cashhack: ${{ secrets.cashhack }}
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python main.py
        env:
          cashhack: ${{ github.event.inputs.cashhack }}
